---
  # we have to use the legacy flavor because we use ES5
  extends: "airbnb/legacy"
  # override (temporarily?) some rules from the "airbnb/legacy" configuration
  rules:
    camelcase: 0
    comma-dangle: 0
    consistent-return: 0
    eqeqeq: 0
    func-names: 0
    indent: 0
    max-len: 0
    no-console: 0
    no-else-return: 0
    no-multi-spaces: 0
    no-nested-ternary: 0
    no-redeclare: 0
    no-shadow: 0
    no-undef: 0
    no-unneeded-ternary: 0
    no-unused-vars: 0
    no-use-before-define: 0
    padded-blocks: 0
    quote-props: 0
    quotes: 0
    space-before-function-paren: 0
    spaced-comment: 0
    strict: 0
    vars-on-top: 0
